name: Build and Test on iOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test on iOS Simulator
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Resolve Swift package dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build and run tests
        run: |
          set -o pipefail
          xcodebuild \
            -scheme SubviewHierarchy \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -sdk iphonesimulator \
            -enableCodeCoverage YES \
            clean build test \
            | xcpretty

